etr/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\loginController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\HomeUserController;
use App\Http\Controllers\ProductsUserController;
use App\Http\Controllers\AboutUserController;
use App\Http\Controllers\ContactUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin/login', [loginController::class,'index']);
Route::post('/admin/check', [loginController::class, 'validate_form'])->name('auth.check');
Route::get('/admin/logout', [loginController::class,'logout']);

//admin
Route::resource('/admin/products', ProductController::class);
Route::resource('/admin/contacts', ContactController::class);
Route::resource('/admin/abouts', AboutController::class);
Route::resource('/admin/homes', HomeController::class);

//user
Route::get('/home', [HomeUserController::class, 'show']);
Route::get('/product', [ProductsUserController::class, 'show']);
Route::get('/about', [AboutUserController::class, 'show']);
Route::get('/contact', [ContactUserController::class, 'show']);

etr/app/Models/Home.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Home extends Model
{
    use HasFactory;

    protected $fillable = [
        'text'
    ];
}

etr/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Home;
use Illuminate\Http\Request;


class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $homes = Home::latest()->paginate(5);
    
        return view('homes.index',compact('homes'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('homes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $request->validate([
            'text' => 'required',
            
        ]);
  
        $input = $request->all();
        Home::create($input);
     
        return redirect()->route('homes.index')
                        ->with('success','Created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Home  $home
     * @return \Illuminate\Http\Response
     */
    public function show(Home $home)
    {
        return view('homes.show',compact('home'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Home  $home
     * @return \Illuminate\Http\Response
     */
    public function edit(Home $home)
    {
        return view('homes.edit',compact('home'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Home  $home
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Home $home)
    {
        $request->validate([
            'text' => 'required'
        ]);
  
        $input = $request->all();
        $home->update($input);
    
        return redirect()->route('homes.index')
                        ->with('success','Text Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Home  $home
     * @return \Illuminate\Http\Response
     */
    public function destroy(Home $home)
    {
        $home->delete();
     
        return redirect()->route('homes.index')
                        ->with('success','Text deleted successfully');
    }
}

etr/resources/views/homes/create.blade.php
@extends('homes.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Create New Home Content</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('homes.index') }}"> Back</a>
        </div>
    </div>
</div>
     
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Oppppsiii!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
     
<form action="{{ route('homes.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Home Content</strong>
                <textarea class="form-control" style="height:150px" name="text" placeholder="Enter text"></textarea>
            </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
     
</form>
@endsection

etr/resources/views/homes/edit.blade.php
@extends('homes.layout')
     
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Home</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('homes.index') }}"> Back</a>
            </div>
        </div>
    </div>
     
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <form action="{{ route('homes.update',$home->id) }}" method="POST" enctype="multipart/form-data"> 
        @csrf
        @method('PUT')
     
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Home Content: </strong>
                    <textarea class="form-control" style="height:150px" name="text" placeholder="Home Content">{{ $home->text }}</textarea>
                </div>
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
     
    </form>
@endsection

etr/resources/views/homes/index.blade.php
@extends('homes.layout')
@section('content')


    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Welcome Admin! </h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('homes.create') }}"> Create Home Content</a>
            </div>
        </div>
    </div>
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
     
     
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Text</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($homes as $home)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $home->text }}</td>
            <td>
                <form action="{{ route('homes.destroy',$home->id) }}" method="POST">
     
                    <a class="btn btn-info" href="{{ route('homes.show',$home->id) }}">Show</a>
      
                    <a class="btn btn-primary" href="{{ route('homes.edit',$home->id) }}">Edit</a>
     
                    @csrf
                    @method('DELETE')
        
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    
    {!! $homes->links() !!}


        
@endsection

etr/resources/views/homes/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Admin Home</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
    <meta charset="utf-8">
    <meta charset="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>
    <link rel="icon" type="image/png" href="/imgs/logo.png" sizes="16x16">

    <style>
        <style>
    body{
      margin: 0;
      padding: 0;
      width: 100%;
      height: 100vh;
      font-family: sans-serif;
      background-size: cover;
      background-position: center;
    }    
    nav{
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100px;
        padding: 10px 90px;
        box-sizing: border-box;
        background: #FD90A3;
        border-bottom: 1px solid #fff;
    }
    nav .current{
        background-color: pink;
    }
    .logo{
        padding: 0px 25px;
        height: -10px;
        float: left;
        opacity: 25%;
    }
    .logo img{
        width: 100px;
        height: 90px;
    }
    nav ul{
        list-style: none;
        float: right;
        margin: 0;
        padding: 0;
        display: flex;
    }
    nav ul li a{
        line-height: 80px;
        color: #fff;
        padding: 12px 30px;
        text-decoration: none;
        font-size: 14px;
        font-weight: bold;
        text-transform: uppercase;        
    }
    nav ul li a:hover{
        background: #ECC4BA;
        border-radius: 6px;
    }
    .table{
        margin-top: 55px;
    }
    h2{
        color: black;
        margin-top: 100px;
        margin-left: 20px;
    }
    .pull-right{
        margin-top: 120px;
        background-color: #FD90A3;
    }
    .pull-right a{
        color: white;
    }
    
    .table th{
        background-color: #FD90A3;
        color: white;
    }
    .btn{
        background-color: #FD90A3;
    }
    </style>

</head>

<body>
  
<div class="container">
    @yield('content')</div>
    <nav>
            <div class= "logo"> <img src="/imgs/logo.png" id="logo"></div>
            <ul>
                <li><a class="current" href="/admin/homes">Home</a></li>
                <li><a href="/admin/products">Products</a></li>
                <li><a href="/admin/abouts">About</a></li>
                <li><a href="/admin/contacts">Contact</a></li>
                <li><a href="/admin/login">Logout</a></li>
            </ul>
        </nav>
</div>
   
</body>
</html>

etr/resources/views/homes/show.blade.php
@extends('homes.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Content</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('homes.index') }}"> Back</a>
            </div>
        </div>
    </div>
     
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Home Content</strong><br>
                {{ $home->text }}
            </div>
        </div>
        
    </div>
@endsection